FROM mysql:5.7

# set timezome
# ENV TZ=Australia/Sydney
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# RUN mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p root mysql --force

# Expose ports.

EXPOSE 3306
