#FROM docker.elastic.co/elasticsearch/elasticsearch:6.2.4
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
RUN bin/elasticsearch-plugin install analysis-smartcn
# CMD ["/opt/elasticsearch/bin/elasticsearch"]
# EXPOSE 9200
# EXPOSE 9300